#!/bin/bash

# Lights up all control panels for Ardour work on the APC mini prior to
# launching JACK and Ardour itself. Each section gets a different color.

# First, find out which HW ID is assigned to the APC mini
APCMINI=`amidi -l | grep "APC MINI" | grep -oP '(?<=hw:)[\d.]+'`

# Make life easier
CMD="amidi -p hw:$APCMINI,0,0 -S"

# Delay for Reverse Light Show
DELAY="sleep 0.05"

# Wait a moment
sleep 1

# Now light up upper left in yellow
$CMD '90 38 00'
$CMD '90 39 00'
$CMD '90 3A 00'
$CMD '90 3B 00'
$CMD '90 30 00'
$CMD '90 31 00'
$CMD '90 32 00'
$CMD '90 33 00'
$CMD '90 28 00'
$CMD '90 29 00'
$CMD '90 2A 00'
$CMD '90 2B 00'
$CMD '90 20 00'
$CMD '90 21 00'
$CMD '90 22 00'
$CMD '90 23 00'

# Upper right in green
$CMD '90 3C 00'
$CMD '90 3D 00'
$CMD '90 3E 00'
$CMD '90 3F 00'
$CMD '90 34 00'
$CMD '90 35 00'
$CMD '90 36 00'
$CMD '90 37 00'
$CMD '90 2C 00'
$CMD '90 2D 00'
$CMD '90 2E 00'
$CMD '90 2F 00'
$CMD '90 24 00'
$CMD '90 25 00'
$CMD '90 26 00'
$CMD '90 27 00'

# Drum Pad in red
$CMD '90 18 00'
$CMD '90 19 00'
$CMD '90 1A 00'
$CMD '90 1B 00'
$CMD '90 10 00'
$CMD '90 11 00'
$CMD '90 12 00'
$CMD '90 13 00'
$CMD '90 08 00'
$CMD '90 09 00'
$CMD '90 0A 00'
$CMD '90 0B 00'
$CMD '90 00 00'
$CMD '90 01 00'
$CMD '90 02 00'
$CMD '90 03 00'

# Light up the function buttons on the right
$CMD '90 52 00'
$CMD '90 53 00'
$CMD '90 54 00'
$CMD '90 55 00'
$CMD '90 56 00'
$CMD '90 57 00'
$CMD '90 58 00'

# That's it
